puentebravo/project2

.eslintignore, .eslintrc.json, .travis.yml, config/config.json, config/middleware/isAuthenticated.js, config/passport.js, models/index.js, models/user.js, package.json, public/js/login.js, public/js/members.js, public/js/signup.js, public/login.html, public/members.html, public/signup.html, public/stylesheets/style.css, routes/api-routes.js, routes/html-routes.js, server.js
=> Added test files

.travis.yml
Hopefully, Travis won't freak out.
=> Updated travis.yml file

README.md, views/layouts/main.handlebars
Added handlebars template skeleton
=> Main handlebars template

views/layouts/main.handlebars
HANDLEBARS: 
- added navbar with inert page links and Login button
- added footer with copyright message.
=> Added navbar, footer to main handlebars template

db/placeholder.txt, db/schema.sql
FILE STRUCTURE: 
- moved schema file into DB folder
=> Indextemplate

config/config.js
CONFIG.JS : 
- added JAWSDB connection information
=> Added JAWSDB configuration to config.js for Heroku deployment

views/index.handlebars, views/partials/jokeoftheday.handlebars
index.handlebars: 
added base code for joke of the day display, referenced partial
jokeoftheday.handlebars: 
added base code to display joke of the day on load
=> Handlebars Index/landing page

routes/html-routes.js
I made the html-routes file and made sure it does not have errors -Adia
=> html-routes.js

views/repunsatory.handlebars
added file: repunsatory.handlebars
Added search bar, filters, and jokes list, as well as #each loop for SQL data and link to list item partial.
=> Wrote view for joke list page, added search bar, filters, list

db/schema.sql
=> schema reconfig

views/partials/placeholder.txt, views/partials/punlistblock.handlebars
VIEWS: 
-added punlistblock partial, ```<li>``` code for rendering joke objects in a list
=> Added punlistblock partial for jokelist rendering

views/partials/authoredList.handlebars, views/partials/punlistblock.handlebars
VIEWS/PARTIALS:
punlistblock: Added unique classes instead of ids for better use with list items; added if/else statement to save button to reflect current user save state
authoredList: added render template for authored jokes, as well as delete button.
=> Profilepage

README.md, package.json
README: 
- added readme text
PACKAGE.JSON: 
- added dotenv npm dependency
=> Added readme text, updated package JSON file with dotenv dependency

models/user.js, package.json
PACKAGE.JSON: 
- added bcrypt dependency
USER.JS: 
- cleaned up ESLINT errors
=> Added bcrypt, cleaned up user.js file

server.js
SERVER.JS: 
- removed reference to html routing file
- cleaned up eslint errors
=> Removed reference to deprecated file, cleaned up formatting

controllers/punController.js
I worked on the punController.js. I am trying to see if someone can help me fix the bugs of this code. I am not sure this is 100% right. This "user" file is the issue I am having. If you would like to make changes, then let me know.
=> punController.js

routes/api-routes.js
api-routes.js:
added get route for landing page, wrote raw SQL query to grab random entry for joke of the day
=> Added get route for main page

routes/routes.js, views/layouts/main.handlebars
setup files for individual styling
=> set up files for multiple stylesheets

config/passport.js, routes/api-routes.js, views/layouts/main.handlebars
Handlebars: 
- modified layout to accept conditional CSS sheets
API routes: 
fixed res.render function in index page get route
=> Sequelizev2

views/index.handlebars, views/layouts/main.handlebars, views/partials/punlistblock.handlebars, views/repunsatory.handlebars
main.handlebars:
- fixed navbar. Will now collapse only on smaller screens
punlistblock.handlebars:
- updated tags to map to isSaved ids. 
repunsatory.handlebars: 
- edited layout of page for better flow, visibility
=> Apiworkings

models/joke.js, models/user.js, routes/api-routes.js, views/index.handlebars, views/layouts/main.handlebars, views/profile.handlebars, views/repunsatory.handlebars
Handlebars: 
modified tags on profile and repunsatory views to work with api routes.
=> Modified tags to work with api routes

views/profile.handlebars
added some image cards. For some reason, my css styling wasn't hitting some of the bootstrap components, so I just styled them in the handlebars file.  If it's a problem, I can fix it later tonight/tomorrow morning.
=> img cards + styling

public/stylesheets/index.css, public/stylesheets/profile.css, public/stylesheets/repunsatory.css, views/layouts/main.handlebars
handlebars: 
- fixed sticky footer. It's actually sticky now. 
Stylesheets: 
- removed custom footer styling
=> Passwordvalidatejs

server.js
Serverjs: 
added user id tracking middleware
=> Added passport user id tracking middleware

config/passport.js, models/user.js, public/js/login.js, routes/api-routes.js, views/index.handlebars, views/signup.handlebars
Added login functionality, linked landing page JS, and modified API  routes to pass landing page JS file
=> Apirouting

public/js/profile.js, routes/api-routes.js
JS: 
- fixed click listener: submit button now functions as expected. 
Routing: 
- fixed /get and /post routes for the profile page. Server now correctly captures the id of the user currently logged in.
=> Profileupdate

views/index.handlebars, views/profile.handlebars, views/repunsatory.handlebars
Phew! I was finally able to the github issue.  Added a couple images to profile.handlebars and updated the relative paths for the other images
=> relative paths + img's

views/layouts/main.handlebars
=> created google font fam + added link to main.handlebars

public/js/profile.js
I am working on the dad jokes api. I am putting the fetch request above line 62. Charlie and I am going to test it if it works
=> profile.js

views/repunsatory.handlebars
=> repunsatory styling
